---
- name: checking the file availability
  hosts: all
  tasks:
    - name: check the information on the file if the file exists
      wins_stat:
        path: C:\\Temp\\test.conf
      register: out
    - name: showing the statistic
      debug:
        var: out
...